Config for AIThinker ESP32-G Gateway
esphome/bluetooth-proxies pull request #47
Opened 2022-11-02 17:39 UTC by mrbubble62

Board comes with u.fl antenna connection, Ethernet, USB serial, 4 LEDs, 5v and 12v power input, reset and boot buttons.
### https://docs.ai-thinker.com/en/blue_tooth_gateway
### https://eadalabs.com/esp32g-smart-ethernet-gateway/

2022-11-02 18:45 UTC, nagyrobi commented
Also on ali: HUF 9,606.24  12%OFF | ESP32-G WiFi+BLE smart gateway Ethernet ESP32-G can be used with WiFi Bluetooth module
https://a.aliexpress.com/_mqiuXSU

2022-11-02 19:08 UTC, jesserockz requested changes
You will need to add this to the static index page and the workflows files so people can actually install from the website.

2022-11-02 19:08 UTC, jesserockz commented on ESP32-G.yaml
> +  package_import_url: github://esphome/bluetooth-proxies/esp32g.yaml@main
This filename does not match
```suggestion
  package_import_url: github://esphome/bluetooth-proxies/ESP32-G.yaml@main
```

2022-11-03 06:28 UTC, mrbubble62 commented
Not sure how to test the static page, I get an error  "Failed to download manifest" when I click on the Connect button for any of the boards.

2022-11-03 07:35 UTC, balloob commented on .github/workflows/ci.yml
> +          - esp32-g.yaml
Add ai thinker to the filename

2022-11-03 07:36 UTC, balloob commented on ESP32-G.yaml
> +  package_import_url: github://esphome/bluetooth-proxies/ESP32-G.yaml@main
Capitalization needs to match the filename.

2022-11-03 07:36 UTC, balloob commented
The PCB image is a) not used and b) 2MB

2022-12-08 07:06 UTC, closed without merging